Repository masters2023-project-06-second-hand/second-hand-be-b, pull requests merged in 2023-09, with the labels that each got.

#21 DB 초기데이터 생성
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/init/DatabaseInitializer.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/CategoryJpaRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/CategoryRepositoryImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/RegionRepositoryImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/out/CategoryRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/out/RegionRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/product/Category.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/region/Region.java
  second-hand-b/src/main/resources/data/category_data.csv
  second-hand-b/src/main/resources/data/region_data.csv
Labels: enhancement

#22 feat: AccessToken 적용
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/config/OAuth2LoginSecurityConfig.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/config/jwt/JwtSignInAuthenticationFilter.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/exception/BusinessExceptionHandler.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/security/JwtAccessToken.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/MemberJpaRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/MemberRepositoryImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/exception/BusinessException.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/exception/ErrorBody.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/exception/ErrorMessage.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/exception/ErrorResponse.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/exception/Errors.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/exception/MemberNotFoundException.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/exception/NotRegisteredMemberException.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/exception/RegionNotFoundException.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/MemberService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/member/Member.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/units/JwtTokenProvider.java
  second-hand-b/src/main/resources/application-oauth2.yml
  second-hand-b/src/main/resources/application.yml
  second-hand-b/src/test/java/com/codesquad/secondhand/SecondHandApplicationTests.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/MemberRegionControllerTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/MemberRegionSteps.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/ProductControllerTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/ProductSteps.java
  second-hand-b/src/test/java/com/codesquad/secondhand/config/SecurityTestConfig.java
  second-hand-b/src/test/java/com/codesquad/secondhand/oauth/OauthServerTestController.java
  second-hand-b/src/test/java/com/codesquad/secondhand/utils/AcceptanceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/utils/AccessTokenRequest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/utils/DatabaseCleanup.java
  second-hand-b/src/test/java/com/codesquad/secondhand/utils/OAuth2AuthorizationTestRequest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/utils/OauthAccessTokenResponse.java
  second-hand-b/src/test/java/com/codesquad/secondhand/utils/OauthProfileResponse.java
  second-hand-b/src/test/java/com/codesquad/secondhand/utils/OauthServerResponses.java
Labels: enhancement

#25 이미지 업로드 및 삭제 기능
  second-hand-b/build.gradle
  second-hand-b/src/main/java/com/codesquad/secondhand/SecondHandApplication.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/ImageController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/init/DatabaseInitializer.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/CategoryRepositoryImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/ImageJpaRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/ImageRepositoryImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/s3/S3StorageService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/ImageUseCase.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/exception/CategoryNotFoundException.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/exception/ImageNotFoundException.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/request/DeleteImageRequest.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/response/ImageInfo.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/response/ProductDetail.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/out/CategoryRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/out/CloudStorageService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/out/ImageRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/CategoryService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/ImageService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/MemberRegionService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/MemberService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/ProductService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/RegionService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/image/Image.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/member/Member.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/product/Category.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/product/Images.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/product/Product.java
  second-hand-b/src/main/resources/application-cloud.yml
  second-hand-b/src/main/resources/application-localdb.yml
  second-hand-b/src/main/resources/application.yml
  second-hand-b/src/main/resources/data/category_data.csv
  second-hand-b/src/main/resources/data/region_data.csv
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/ImageControllerTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/MemberRegionControllerTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/MemberRegionSteps.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/ProductControllerTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/ProductSteps.java
  second-hand-b/src/test/resources/image/test.jpg
  second-hand-b/src/test/resources/image/test2.jpg
Labels: enhancement

#26 로그인 기능 구현
  second-hand-b/src/main/java/com/codesquad/secondhand/SecondHandApplication.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/AuthController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/MemberController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/config/OAuth2LoginSecurityConfig.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/config/jwt/JwtSignInAuthenticationFilter.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/config/jwt/JwtSignUpAuthenticationFilter.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/exception/BusinessExceptionHandler.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/init/DatabaseInitializer.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/CategoryRepositoryImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/MemberRepositoryImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/ProductRepositoryImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/RefreshTokenRepositoryImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/RegionRepositoryImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/imports/CategoryJpaRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/imports/MemberJpaRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/imports/ProductJpaRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/imports/RefreshTokenJpaRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/imports/RegionJpaRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/AuthUseCase.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/MemberUseCase.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/exception/TokenExpiredException.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/request/SignUpRequest.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/response/Tokens.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/out/RefreshTokenRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/AuthService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/MemberService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/auth/RefreshToken.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/member/Member.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/units/JwtTokenProvider.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/AuthAcceptanceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/AuthControllerTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/MemberSteps.java
  second-hand-b/src/test/java/com/codesquad/secondhand/config/SecurityTestConfig.java
  second-hand-b/src/test/java/com/codesquad/secondhand/oauth/OauthServerTestController.java
  second-hand-b/src/test/java/com/codesquad/secondhand/oauth/TestSecurityContextFactory.java
  second-hand-b/src/test/java/com/codesquad/secondhand/oauth/WithTestUser.java
  second-hand-b/src/test/java/com/codesquad/secondhand/utils/AcceptanceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/utils/AccessTokenRequest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/utils/OAuth2AuthorizationTestRequest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/utils/OauthAccessTokenResponse.java
  second-hand-b/src/test/java/com/codesquad/secondhand/utils/OauthProfileResponse.java
  second-hand-b/src/test/java/com/codesquad/secondhand/utils/OauthServerResponses.java
Labels: enhancement

#34 관심상품 및 판매상품 기능 구현
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/MemberController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/ProductController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/config/OAuth2LoginSecurityConfig.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/config/jwt/JwtSignInAuthenticationFilter.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/config/jwt/JwtSignUpAuthenticationFilter.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/CategoryRepositoryImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/ProductRepositoryImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/imports/CategoryJpaRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/imports/ProductJpaRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/MemberUseCase.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/ProductUseCase.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/exception/PermissionDeniedException.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/exception/ProductNotFoundException.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/request/ToggleProductLikeStatusRequest.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/response/CategorySimpleDetail.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/out/CategoryRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/out/ProductRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/AuthService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/CategoryService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/ImageService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/MemberService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/ProductService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/RegionService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/member/Likes.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/member/Member.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/member/MemberRegions.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/product/Category.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/product/Images.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/product/Status.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/units/JwtTokenProvider.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/AuthAcceptanceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/AuthControllerTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/AuthSteps.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/ImageControllerTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/MemberControllerTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/MemberRegionControllerTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/MemberSteps.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/ProductControllerTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/ProductSteps.java
  second-hand-b/src/test/java/com/codesquad/secondhand/application/service/in/AuthServiceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/application/service/in/CategoryServiceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/application/service/in/ImageServiceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/application/service/in/MemberServiceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/application/service/in/ProductServiceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/application/service/in/RegionServiceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/utils/AcceptanceTest.java
Labels: enhancement

#36 지역 목록, 카테고리 목록, 상품 목록 구현
  second-hand-b/build.gradle
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/CategoryController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/ImageController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/ProductController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/RegionController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/config/CustomPageableConfig.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/CategoryRepositoryImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/ImageRepositoryImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/ProductRepositoryImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/RegionRepositoryImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/imports/ImageJpaRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/imports/ProductJpaRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/imports/RegionJpaRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/CategoryUseCase.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/ImageUseCase.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/ProductUseCase.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/RegionUseCase.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/response/CategoryDetail.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/response/ProductDetail.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/response/ProductInfo.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/response/ProductWriter.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/out/CategoryRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/out/ProductRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/out/RegionRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/CategoryService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/ImageService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/ProductService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/RegionService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/member/MemberRegions.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/product/Category.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/product/Images.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/product/Product.java
  second-hand-b/src/main/resources/data/category_data.csv
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/CategoryAcceptanceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/CategorySteps.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/ImageAcceptanceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/MemberRegionAcceptanceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/MemberRegionSteps.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/ProductAcceptanceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/ProductSteps.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/RegionAcceptanceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/utils/AcceptanceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/utils/S3MockConfig.java
Labels: enhancement

#38 이미지 테스트 오류 수정
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/ImageController.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/ImageAcceptanceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/ProductSteps.java
Labels: bug

#40 Be server cicd
  .github/workflows/be-cd.yml
  .github/workflows/be-ci.yml
  .github/workflows/fe-cd.yml
  .github/workflows/nginx-cd.yml
  Dockerfile.be
  Dockerfile.fe
  Dockerfile.nginx
  nginx.conf
  second-hand-b/build.gradle
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/AuthController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/config/AuthenticationResponseHandler.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/config/AuthenticationResponseHandlerImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/config/OAuth2LoginSecurityConfig.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/config/OAuth2LoginSuccessHandler.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/exception/BusinessExceptionHandler.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/exception/CategoryNotFoundException.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/exception/Errors.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/exception/ImageNotFoundException.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/exception/MemberNotFoundException.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/exception/NotRegisteredMemberException.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/exception/PermissionDeniedException.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/exception/ProductNotFoundException.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/exception/RegionNotFoundException.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/exception/TokenExpiredException.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/response/Tokens.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/AuthService.java
  second-hand-b/src/main/resources/application.yml
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/AuthControllerTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/config/AuthenticationResponseHandlerImplTest.java
Labels: enhancement

#41 조회 기능 리팩토링 및 상품 삭제 기능 구현
  second-hand-b/build.gradle
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/ImageController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/MemberController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/ProductController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/RegionController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/config/CustomPageableConfig.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/MemberRepositoryImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/ProductRepositoryImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/RefreshTokenRepositoryImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/RegionRepositoryImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/imports/MemberCrudRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/imports/ProductCrudRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/imports/ProductJpaRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/imports/RefreshTokenCrudRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/imports/RegionCrudRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/CloudUseCase.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/ImageUseCase.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/MemberUseCase.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/ProductUseCase.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/RegionUseCase.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/response/RegionInfos.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/out/ProductRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/CloudService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/ImageService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/MemberService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/ProductService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/RegionService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/member/Likes.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/member/Member.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/product/Category.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/product/Images.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/product/Product.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/ImageAcceptanceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/MemberAcceptanceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/MemberSteps.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/ProductAcceptanceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/ProductSteps.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/RegionAcceptanceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/utils/AcceptanceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/utils/S3MockConfig.java
Labels: enhancement

#44 Product 리펙토링
  .github/workflows/be-cd.yml
  .github/workflows/be-ci.yml
  second-hand-b/build.gradle
  second-hand-b/src/docs/asciidoc/index.adoc
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/AuthController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/CategoryController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/ImageController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/MemberRegionController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/ProductController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/RestDocsController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/config/AuthenticationResponseHandlerImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/config/OAuth2LoginSecurityConfig.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/exception/GlobalExceptionHandler.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/request/ModifyStatusRequest.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/request/ProductCreateRequest.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/request/ProductModifyRequest.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/request/RefreshTokenRequest.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/request/annotation/CategoryId.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/request/annotation/ImagesId.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/request/annotation/ImagesIdValidator.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/request/annotation/ProductContent.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/request/annotation/ProductName.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/request/annotation/ProductPrice.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/request/annotation/RegionId.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/AuthUseCase.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/ProductUseCase.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/AuthService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/CategoryService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/ImageService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/MemberService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/RegionService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/exception/BadRequestException.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/exception/ErrorCode.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/exception/InvalidEntityStateException.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/exception/MinimumImageRequirementException.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/image/ImageMapper.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/prodcut/ProductMapper.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/prodcut/ProductService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/prodcut/ProductUnits.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/product/Images.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/product/Product.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/product/Status.java
  second-hand-b/src/main/resources/messages.properties
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/AuthControllerTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/ProductAcceptanceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/ProductSteps.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/request/annotation/ImagesIdValidatorTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/application/service/in/ImageServiceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/application/service/in/MemberServiceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/application/service/in/ProductServiceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/application/service/in/RegionServiceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/application/service/in/prodcut/ProductMapperTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/domain/product/ImagesTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/domain/product/ProductTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/domain/product/ProductTestUtils.java
  second-hand-b/src/test/java/com/codesquad/secondhand/domain/product/StatusTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/utils/AcceptanceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/utils/RestDocsUtils.java
Labels: enhancement

#47 refactor: CD에서 build에 테스트 추가
  .github/workflows/be-cd.yml
Labels: bug

#50 BE CI/CD에서 Gradle 의존성에 Cash 적용
  .github/workflows/be-cd.yml
  .github/workflows/be-ci.yml
Labels: enhancement

#51 refactor: BE CI/CD에서 Cash 적용 수정
  .github/workflows/be-cd.yml
  .github/workflows/be-ci.yml
Labels: bug

#52 refactor: BE CI/CD에서 Cash 적용 재수정
  .github/workflows/be-cd.yml
  .github/workflows/be-ci.yml
  second-hand-b/gradle/wrapper/gradle-wrapper.properties
Labels: documentation, enhancement

#56 feat: SignUp구현
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/AuthController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/config/OAuth2LoginSecurityConfig.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/config/jwt/JwtSignInAuthenticationFilter.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/config/jwt/JwtSignUpAuthenticationFilter.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/RefreshTokenRepositoryImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/imports/RefreshTokenCrudRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/AuthUseCase.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/out/RefreshTokenRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/schedule/AuthSchedule.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/AuthService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/exception/ErrorCode.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/exception/InvalidRefreshTokenException.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/auth/RefreshToken.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/units/JwtTokenProvider.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/AuthControllerTest.java
Labels: enhancement

#58 chore: gradle build 설정 변경
  second-hand-b/build.gradle
Labels: enhancement

#65 9월 20일 머지
  fe/src/App.tsx
  fe/src/api/auth/login.tsx
  fe/src/api/product/product.tsx
  fe/src/api/region/region.tsx
  fe/src/atoms/toastAtom.tsx
  fe/src/components/Dropdown/ReigonDropdown.tsx
  fe/src/components/Modal/RegionSettingModal.tsx
  fe/src/components/Toast/Toast.tsx
  fe/src/components/Toast/useToast.tsx
  fe/src/pages/CallbackPage.tsx
  fe/src/pages/HomePage.tsx
  fe/src/pages/Product/AddPage.tsx
  fe/src/pages/Product/DetailPage.tsx
  fe/src/pages/Product/ProductPage.tsx
  fe/src/routes/router.tsx
  fe/src/utils/extractRegionName.tsx
Labels: enhancement

#67 feat:signout
  .github/workflows/be-ci.yml
  README.md
  second-hand-b/build.gradle
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/controller/MemberController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/controller/MemberProductController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/controller/MemberRegionController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/controller/ProductController.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/response/product/ProductsInfo.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/in/web/security/filter/JwtSignInAuthenticationFilter.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/ProductRepositoryImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/RefreshTokenRepositoryImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/RegionRepositoryImpl.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/imports/CategoryJpaRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/imports/ProductCrudRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/adapter/out/persistence/imports/RefreshTokenCrudRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/MemberUseCase.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/MyRegionsUseCase.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/in/ProductUseCase.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/out/ProductRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/out/RefreshTokenRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/port/out/RegionRepository.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/AuthService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/CategoryService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/MemberFacade.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/MemberService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/MyRegionsService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/exception/ErrorCode.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/exception/MinimumRegionRequirementException.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/prodcut/ProductFacade.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/prodcut/ProductService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/application/service/in/region/RegionService.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/member/Likes.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/member/Member.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/member/MemberRegions.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/member/MyRegions.java
  second-hand-b/src/main/java/com/codesquad/secondhand/domain/product/Product.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/MemberRegionSteps.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/MemberSteps.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/MyRegionAcceptanceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/ProductAcceptanceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/adapter/in/web/ProductSteps.java
  second-hand-b/src/test/java/com/codesquad/secondhand/application/service/in/MemberRegionServiceTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/domain/member/MemberRegionsTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/domain/member/MemberTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/domain/member/MyRegionsTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/domain/product/ProductTest.java
  second-hand-b/src/test/java/com/codesquad/secondhand/domain/product/ProductTestUtils.java
  second-hand-b/src/test/java/com/codesquad/secondhand/utils/AcceptanceTest.java
Labels: enhancement
